spring:
  application:
   name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_user_service
    username: root
    password: Rawat@123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect